create database cojaoficio;


create table Usuarios(
IdUsuario int  auto_increment primary key not null,
Username  varchar(255)	not null,
Password  varchar(255)
);


create table Informacion_Basica(
IdUsuario int primary key not null,
NumeroDocumento int not null,
IdDocumento   int not null,
Nombres varchar(255) not null,
ApellidoPaterno varchar(255) not null,
ApellidoMaterno varchar(255) not null,
Movil varchar(255) not null,
Telefono varchar(255)  null,
Email  varchar(255)  null,
Direccion varchar(255)  null,
IdCiudad int not null,
IdDepartamento int not null
);


create table Tipo_Documento(
IdDocumento int auto_increment primary key,
TipoDocumento varchar(5) not null,
Descripcion  varchar(50) not null
);


Create table Ciudades (
IdCiudad int auto_increment,
Descripcion varchar(255) not null,
IdDepartamento int not null,
constraint Pk_IdCiudad primary key (Idciudad,Descripcion,IdDepartamento)
);


Create table Departamentos (
IdDepartamento int auto_increment Primary Key,
Descripcion varchar(255) not null
);

alter table informacion_basica drop foreign key fk_informacion_basica_usuarios;
alter table informacion_basica drop foreign key fk_informacion_basica_Tipo_Documento;
alter table informacion_basica drop foreign key fk_informacion_basica_Ciudades;
alter table informacion_basica drop foreign key fk_informacion_basica_Departamentos;

alter table informacion_basica add constraint fk_informacion_basica_usuarios foreign key (IdUsuario) references usuarios (IdUsuario);
alter table informacion_basica add constraint fk_informacion_basica_Tipo_Documento foreign key (IdDocumento) references tipo_documento (IdDocumento);
alter table informacion_basica add constraint fk_informacion_basica_Ciudades foreign key (IdCiudad) references ciudades (IdCiudad);
alter table informacion_basica add constraint fk_informacion_basica_Departamentos foreign key (IdDepartamento) references departamentos (IdDepartamento);



Insert Into tipo_documento (TipoDocumento, Descripcion) Values ('CC', 'Cedula De Ciudadania');
Insert Into tipo_documento (TipoDocumento, Descripcion) Values ('CE', 'Cedula De Extranjeria');
Insert Into tipo_documento (TipoDocumento, Descripcion) Values ('PS', 'Pasaporte');


Insert Into Departamentos values (	05,	'ANTIOQUIA');
Insert Into Departamentos values (	08,	'ATLANTICO');
Insert Into Departamentos values (	11,	'BOGOTA');
Insert Into Departamentos values (	13,	'BOLIVAR');
Insert Into Departamentos values (	15,	'BOYACA');
Insert Into Departamentos values (	17,	'CALDAS');
Insert Into Departamentos values (	18,	'CAQUETA');
Insert Into Departamentos values (	19,	'CAUCA');
Insert Into Departamentos values (	20,	'CESAR');
Insert Into Departamentos values (	23,	'CORDOBA');
Insert Into Departamentos values (	25,	'CUNDINAMARCA');
Insert Into Departamentos values (	27,	'CHOCO');
Insert Into Departamentos values (	41,	'HUILA');
Insert Into Departamentos values (	44,	'LA GUAJIRA');
Insert Into Departamentos values (	47,	'MAGDALENA');
Insert Into Departamentos values (	50,	'META');
Insert Into Departamentos values (	52,	'NARIÑO');
Insert Into Departamentos values (	54,	'N. DE SANTANDER');
Insert Into Departamentos values (	63,	'QUINDIO');
Insert Into Departamentos values (	66,	'RISARALDA');
Insert Into Departamentos values (	68,	'SANTANDER');
Insert Into Departamentos values (	70,	'SUCRE');
Insert Into Departamentos values (	73,	'TOLIMA');
Insert Into Departamentos values (	76,	'VALLE DEL CAUCA');
Insert Into Departamentos values (	81,	'ARAUCA');
Insert Into Departamentos values (	85,	'CASANARE');
Insert Into Departamentos values (	86,	'PUTUMAYO');
Insert Into Departamentos values (	88,	'SAN ANDRES');
Insert Into Departamentos values (	91,	'AMAZONAS');
Insert Into Departamentos values (	94,	'GUAINIA');
Insert Into Departamentos values (	95,	'GUAVIARE');
Insert Into Departamentos values (	97,	'VAUPES');
Insert Into Departamentos values (	99,	'VICHADA');


Insert Into Ciudades Values (	001,	'MEDELLIN',	05);
Insert Into Ciudades Values (	002,	'ABEJORRAL',	05);
Insert Into Ciudades Values (	004,	'ABRIAQUI',	05);
Insert Into Ciudades Values (	021,	'ALEJANDRIA',	05);
Insert Into Ciudades Values (	030,	'AMAGA',	05);
Insert Into Ciudades Values (	031,	'AMALFI',	05);
Insert Into Ciudades Values (	034,	'ANDES',	05);
Insert Into Ciudades Values (	036,	'ANGELOPOLIS',	05);
Insert Into Ciudades Values (	038,	'ANGOSTURA',	05);
Insert Into Ciudades Values (	040,	'ANORI',	05);
Insert Into Ciudades Values (	042,	'SANTAFE DE ANTIOQUIA',	05);
Insert Into Ciudades Values (	044,	'ANZA',	05);
Insert Into Ciudades Values (	045,	'APARTADO',	05);
Insert Into Ciudades Values (	051,	'ARBOLETES',	05);
Insert Into Ciudades Values (	055,	'ARGELIA',	05);
Insert Into Ciudades Values (	059,	'ARMENIA',	05);
Insert Into Ciudades Values (	079,	'BARBOSA',	05);
Insert Into Ciudades Values (	086,	'BELMIRA',	05);
Insert Into Ciudades Values (	088,	'BELLO',	05);
Insert Into Ciudades Values (	091,	'BETANIA',	05);
Insert Into Ciudades Values (	093,	'BETULIA',	05);
Insert Into Ciudades Values (	101,	'CIUDAD BOLIVAR',	05);
Insert Into Ciudades Values (	107,	'BRICEÑO',	05);
Insert Into Ciudades Values (	113,	'BURITICA',	05);
Insert Into Ciudades Values (	120,	'CACERES',	05);
Insert Into Ciudades Values (	125,	'CAICEDO',	05);
Insert Into Ciudades Values (	129,	'CALDAS',	05);
Insert Into Ciudades Values (	134,	'CAMPAMENTO',	05);
Insert Into Ciudades Values (	138,	'CAÑASGORDAS',	05);
Insert Into Ciudades Values (	142,	'CARACOLI',	05);
Insert Into Ciudades Values (	145,	'CARAMANTA',	05);
Insert Into Ciudades Values (	147,	'CAREPA',	05);
Insert Into Ciudades Values (	148,	'EL CARMEN DE VIBORAL',	05);
Insert Into Ciudades Values (	150,	'CAROLINA',	05);
Insert Into Ciudades Values (	154,	'CAUCASIA',	05);
Insert Into Ciudades Values (	172,	'CHIGORODO',	05);
Insert Into Ciudades Values (	190,	'CISNEROS',	05);
Insert Into Ciudades Values (	197,	'COCORNA',	05);
Insert Into Ciudades Values (	206,	'CONCEPCION',	05);
Insert Into Ciudades Values (	209,	'CONCORDIA',	05);
Insert Into Ciudades Values (	212,	'COPACABANA',	05);
Insert Into Ciudades Values (	234,	'DABEIBA',	05);
Insert Into Ciudades Values (	237,	'DON MATIAS',	05);
Insert Into Ciudades Values (	240,	'EBEJICO',	05);
Insert Into Ciudades Values (	250,	'EL BAGRE',	05);
Insert Into Ciudades Values (	264,	'ENTRERRIOS',	05);
Insert Into Ciudades Values (	266,	'ENVIGADO',	05);
Insert Into Ciudades Values (	282,	'FREDONIA',	05);
Insert Into Ciudades Values (	284,	'FRONTINO',	05);
Insert Into Ciudades Values (	306,	'GIRALDO',	05);
Insert Into Ciudades Values (	308,	'GIRARDOTA',	05);
Insert Into Ciudades Values (	310,	'GOMEZ PLATA',	05);
Insert Into Ciudades Values (	313,	'GRANADA',	05);
Insert Into Ciudades Values (	315,	'GUADALUPE',	05);
Insert Into Ciudades Values (	318,	'GUARNE',	05);
Insert Into Ciudades Values (	321,	'GUATAPE',	05);
Insert Into Ciudades Values (	347,	'HELICONIA',	05);
Insert Into Ciudades Values (	353,	'HISPANIA',	05);
Insert Into Ciudades Values (	360,	'ITAGUI',	05);
Insert Into Ciudades Values (	361,	'ITUANGO',	05);
Insert Into Ciudades Values (	364,	'JARDIN',	05);
Insert Into Ciudades Values (	368,	'JERICO',	05);
Insert Into Ciudades Values (	376,	'LA CEJA',	05);
Insert Into Ciudades Values (	380,	'LA ESTRELLA',	05);
Insert Into Ciudades Values (	390,	'LA PINTADA',	05);
Insert Into Ciudades Values (	400,	'LA UNION',	05);
Insert Into Ciudades Values (	411,	'LIBORINA',	05);
Insert Into Ciudades Values (	425,	'MACEO',	05);
Insert Into Ciudades Values (	440,	'MARINILLA',	05);
Insert Into Ciudades Values (	467,	'MONTEBELLO',	05);
Insert Into Ciudades Values (	475,	'MURINDO',	05);
Insert Into Ciudades Values (	480,	'MUTATA',	05);
Insert Into Ciudades Values (	483,	'NARIÑO',	05);
Insert Into Ciudades Values (	490,	'NECOCLI',	05);
Insert Into Ciudades Values (	495,	'NECHI',	05);
Insert Into Ciudades Values (	501,	'OLAYA',	05);
Insert Into Ciudades Values (	541,	'PEÐOL',	05);
Insert Into Ciudades Values (	543,	'PEQUE',	05);
Insert Into Ciudades Values (	576,	'PUEBLORRICO',	05);
Insert Into Ciudades Values (	579,	'PUERTO BERRIO',	05);
Insert Into Ciudades Values (	585,	'PUERTO NARE',	05);
Insert Into Ciudades Values (	591,	'PUERTO TRIUNFO',	05);
Insert Into Ciudades Values (	604,	'REMEDIOS',	05);
Insert Into Ciudades Values (	607,	'RETIRO',	05);
Insert Into Ciudades Values (	615,	'RIONEGRO',	05);
Insert Into Ciudades Values (	628,	'SABANALARGA',	05);
Insert Into Ciudades Values (	631,	'SABANETA',	05);
Insert Into Ciudades Values (	642,	'SALGAR',	05);
Insert Into Ciudades Values (	647,	'SAN ANDRES DE CUERQUIA',	05);
Insert Into Ciudades Values (	649,	'SAN CARLOS',	05);
Insert Into Ciudades Values (	652,	'SAN FRANCISCO',	05);
Insert Into Ciudades Values (	656,	'SAN JERONIMO',	05);
Insert Into Ciudades Values (	658,	'SAN JOSE DE LA MONTAÑA',	05);
Insert Into Ciudades Values (	659,	'SAN JUAN DE URABA',	05);
Insert Into Ciudades Values (	660,	'SAN LUIS',	05);
Insert Into Ciudades Values (	664,	'SAN PEDRO',	05);
Insert Into Ciudades Values (	665,	'SAN PEDRO DE URABA',	05);
Insert Into Ciudades Values (	667,	'SAN RAFAEL',	05);
Insert Into Ciudades Values (	670,	'SAN ROQUE',	05);
Insert Into Ciudades Values (	674,	'SAN VICENTE',	05);
Insert Into Ciudades Values (	679,	'SANTA BARBARA',	05);
Insert Into Ciudades Values (	686,	'SANTA ROSA DE OSOS',	05);
Insert Into Ciudades Values (	690,	'SANTO DOMINGO',	05);
Insert Into Ciudades Values (	697,	'EL SANTUARIO',	05);
Insert Into Ciudades Values (	736,	'SEGOVIA',	05);
Insert Into Ciudades Values (	756,	'SONSON',	05);
Insert Into Ciudades Values (	761,	'SOPETRAN',	05);
Insert Into Ciudades Values (	789,	'TAMESIS',	05);
Insert Into Ciudades Values (	790,	'TARAZA',	05);
Insert Into Ciudades Values (	792,	'TARSO',	05);
Insert Into Ciudades Values (	809,	'TITIRIBI',	05);
Insert Into Ciudades Values (	819,	'TOLEDO',	05);
Insert Into Ciudades Values (	837,	'TURBO',	05);
Insert Into Ciudades Values (	842,	'URAMITA',	05);
Insert Into Ciudades Values (	847,	'URRAO',	05);
Insert Into Ciudades Values (	854,	'VALDIVIA',	05);
Insert Into Ciudades Values (	856,	'VALPARAISO',	05);
Insert Into Ciudades Values (	858,	'VEGACHI',	05);
Insert Into Ciudades Values (	861,	'VENECIA',	05);
Insert Into Ciudades Values (	873,	'VIGIA DEL FUERTE',	05);
Insert Into Ciudades Values (	885,	'YALI',	05);
Insert Into Ciudades Values (	887,	'YARUMAL',	05);
Insert Into Ciudades Values (	890,	'YOLOMBO',	05);
Insert Into Ciudades Values (	893,	'YONDO',	05);
Insert Into Ciudades Values (	895,	'ZARAGOZA',	05);
Insert Into Ciudades Values (	001,	'BARRANQUILLA',	08);
Insert Into Ciudades Values (	078,	'BARANOA',	08);
Insert Into Ciudades Values (	137,	'CAMPO DE LA CRUZ',	08);
Insert Into Ciudades Values (	141,	'CANDELARIA',	08);
Insert Into Ciudades Values (	296,	'GALAPA',	08);
Insert Into Ciudades Values (	372,	'JUAN DE ACOSTA',	08);
Insert Into Ciudades Values (	421,	'LURUACO',	08);
Insert Into Ciudades Values (	433,	'MALAMBO',	08);
Insert Into Ciudades Values (	436,	'MANATI',	08);
Insert Into Ciudades Values (	520,	'PALMAR DE VARELA',	08);
Insert Into Ciudades Values (	549,	'PIOJO',	08);
Insert Into Ciudades Values (	558,	'POLONUEVO',	08);
Insert Into Ciudades Values (	560,	'PONEDERA',	08);
Insert Into Ciudades Values (	573,	'PUERTO COLOMBIA',	08);
Insert Into Ciudades Values (	606,	'REPELON',	08);
Insert Into Ciudades Values (	634,	'SABANAGRANDE',	08);
Insert Into Ciudades Values (	638,	'SABANALARGA',	08);
Insert Into Ciudades Values (	675,	'SANTA LUCIA',	08);
Insert Into Ciudades Values (	685,	'SANTO TOMAS',	08);
Insert Into Ciudades Values (	758,	'SOLEDAD',	08);
Insert Into Ciudades Values (	770,	'SUAN',	08);
Insert Into Ciudades Values (	832,	'TUBARA',	08);
Insert Into Ciudades Values (	849,	'USIACURI',	08);
Insert Into Ciudades Values (	001,	'BOGOTA, D.C.',	11);
Insert Into Ciudades Values (	001,	'CARTAGENA',	13);
Insert Into Ciudades Values (	006,	'ACHI',	13);
Insert Into Ciudades Values (	030,	'ALTOS DEL ROSARIO',	13);
Insert Into Ciudades Values (	042,	'ARENAL',	13);
Insert Into Ciudades Values (	052,	'ARJONA',	13);
Insert Into Ciudades Values (	062,	'ARROYOHONDO',	13);
Insert Into Ciudades Values (	074,	'BARRANCO DE LOBA',	13);
Insert Into Ciudades Values (	140,	'CALAMAR',	13);
Insert Into Ciudades Values (	160,	'CANTAGALLO',	13);
Insert Into Ciudades Values (	188,	'CICUCO',	13);
Insert Into Ciudades Values (	212,	'CORDOBA',	13);
Insert Into Ciudades Values (	222,	'CLEMENCIA',	13);
Insert Into Ciudades Values (	244,	'EL CARMEN DE BOLIVAR',	13);
Insert Into Ciudades Values (	248,	'EL GUAMO',	13);
Insert Into Ciudades Values (	268,	'EL PEÑON',	13);
Insert Into Ciudades Values (	300,	'HATILLO DE LOBA',	13);
Insert Into Ciudades Values (	430,	'MAGANGUE',	13);
Insert Into Ciudades Values (	433,	'MAHATES',	13);
Insert Into Ciudades Values (	440,	'MARGARITA',	13);
Insert Into Ciudades Values (	442,	'MARIA LA BAJA',	13);
Insert Into Ciudades Values (	458,	'MONTECRISTO',	13);
Insert Into Ciudades Values (	468,	'MOMPOS',	13);
Insert Into Ciudades Values (	490,	'NOROSI',	13);
Insert Into Ciudades Values (	473,	'MORALES',	13);
Insert Into Ciudades Values (	549,	'PINILLOS',	13);
Insert Into Ciudades Values (	580,	'REGIDOR',	13);
Insert Into Ciudades Values (	600,	'RIO VIEJO',	13);
Insert Into Ciudades Values (	620,	'SAN CRISTOBAL',	13);
Insert Into Ciudades Values (	647,	'SAN ESTANISLAO',	13);
Insert Into Ciudades Values (	650,	'SAN FERNANDO',	13);
Insert Into Ciudades Values (	654,	'SAN JACINTO',	13);
Insert Into Ciudades Values (	655,	'SAN JACINTO DEL CAUCA',	13);
Insert Into Ciudades Values (	657,	'SAN JUAN NEPOMUCENO',	13);
Insert Into Ciudades Values (	667,	'SAN MARTIN DE LOBA',	13);
Insert Into Ciudades Values (	670,	'SAN PABLO',	13);
Insert Into Ciudades Values (	673,	'SANTA CATALINA',	13);
Insert Into Ciudades Values (	683,	'SANTA ROSA',	13);
Insert Into Ciudades Values (	688,	'SANTA ROSA DEL SUR',	13);
Insert Into Ciudades Values (	744,	'SIMITI',	13);
Insert Into Ciudades Values (	760,	'SOPLAVIENTO',	13);
Insert Into Ciudades Values (	780,	'TALAIGUA NUEVO',	13);
Insert Into Ciudades Values (	810,	'TIQUISIO',	13);
Insert Into Ciudades Values (	836,	'TURBACO',	13);
Insert Into Ciudades Values (	838,	'TURBANA',	13);
Insert Into Ciudades Values (	873,	'VILLANUEVA',	13);
Insert Into Ciudades Values (	894,	'ZAMBRANO',	13);
Insert Into Ciudades Values (	001,	'TUNJA',	15);
Insert Into Ciudades Values (	022,	'ALMEIDA',	15);
Insert Into Ciudades Values (	047,	'AQUITANIA',	15);
Insert Into Ciudades Values (	051,	'ARCABUCO',	15);
Insert Into Ciudades Values (	087,	'BELEN',	15);
Insert Into Ciudades Values (	090,	'BERBEO',	15);
Insert Into Ciudades Values (	092,	'BETEITIVA',	15);
Insert Into Ciudades Values (	097,	'BOAVITA',	15);
Insert Into Ciudades Values (	104,	'BOYACA',	15);
Insert Into Ciudades Values (	106,	'BRICEÑO',	15);
Insert Into Ciudades Values (	109,	'BUENAVISTA',	15);
Insert Into Ciudades Values (	114,	'BUSBANZA',	15);
Insert Into Ciudades Values (	131,	'CALDAS',	15);
Insert Into Ciudades Values (	135,	'CAMPOHERMOSO',	15);
Insert Into Ciudades Values (	162,	'CERINZA',	15);
Insert Into Ciudades Values (	172,	'CHINAVITA',	15);
Insert Into Ciudades Values (	176,	'CHIQUINQUIRA',	15);
Insert Into Ciudades Values (	180,	'CHISCAS',	15);
Insert Into Ciudades Values (	183,	'CHITA',	15);
Insert Into Ciudades Values (	185,	'CHITARAQUE',	15);
Insert Into Ciudades Values (	187,	'CHIVATA',	15);
Insert Into Ciudades Values (	189,	'CIENEGA',	15);
Insert Into Ciudades Values (	204,	'COMBITA',	15);
Insert Into Ciudades Values (	212,	'COPER',	15);
Insert Into Ciudades Values (	215,	'CORRALES',	15);
Insert Into Ciudades Values (	218,	'COVARACHIA',	15);
Insert Into Ciudades Values (	223,	'CUBARA',	15);
Insert Into Ciudades Values (	224,	'CUCAITA',	15);
Insert Into Ciudades Values (	226,	'CUITIVA',	15);
Insert Into Ciudades Values (	232,	'CHIQUIZA',	15);
Insert Into Ciudades Values (	236,	'CHIVOR',	15);
Insert Into Ciudades Values (	238,	'DUITAMA',	15);
Insert Into Ciudades Values (	244,	'EL COCUY',	15);
Insert Into Ciudades Values (	248,	'EL ESPINO',	15);
Insert Into Ciudades Values (	272,	'FIRAVITOBA',	15);
Insert Into Ciudades Values (	276,	'FLORESTA',	15);
Insert Into Ciudades Values (	293,	'GACHANTIVA',	15);
Insert Into Ciudades Values (	296,	'GAMEZA',	15);
Insert Into Ciudades Values (	299,	'GARAGOA',	15);
Insert Into Ciudades Values (	317,	'GUACAMAYAS',	15);
Insert Into Ciudades Values (	322,	'GUATEQUE',	15);
Insert Into Ciudades Values (	325,	'GUAYATA',	15);
Insert Into Ciudades Values (	332,	'GsICAN',	15);
Insert Into Ciudades Values (	362,	'IZA',	15);
Insert Into Ciudades Values (	367,	'JENESANO',	15);
Insert Into Ciudades Values (	368,	'JERICO',	15);
Insert Into Ciudades Values (	377,	'LABRANZAGRANDE',	15);
Insert Into Ciudades Values (	380,	'LA CAPILLA',	15);
Insert Into Ciudades Values (	401,	'LA VICTORIA',	15);
Insert Into Ciudades Values (	403,	'LA UVITA',	15);
Insert Into Ciudades Values (	407,	'VILLA DE LEYVA',	15);
Insert Into Ciudades Values (	425,	'MACANAL',	15);
Insert Into Ciudades Values (	442,	'MARIPI',	15);
Insert Into Ciudades Values (	455,	'MIRAFLORES',	15);
Insert Into Ciudades Values (	464,	'MONGUA',	15);
Insert Into Ciudades Values (	466,	'MONGUI',	15);
Insert Into Ciudades Values (	469,	'MONIQUIRA',	15);
Insert Into Ciudades Values (	476,	'MOTAVITA',	15);
Insert Into Ciudades Values (	480,	'MUZO',	15);
Insert Into Ciudades Values (	491,	'NOBSA',	15);
Insert Into Ciudades Values (	494,	'NUEVO COLON',	15);
Insert Into Ciudades Values (	500,	'OICATA',	15);
Insert Into Ciudades Values (	507,	'OTANCHE',	15);
Insert Into Ciudades Values (	511,	'PACHAVITA',	15);
Insert Into Ciudades Values (	514,	'PAEZ',	15);
Insert Into Ciudades Values (	516,	'PAIPA',	15);
Insert Into Ciudades Values (	518,	'PAJARITO',	15);
Insert Into Ciudades Values (	522,	'PANQUEBA',	15);
Insert Into Ciudades Values (	531,	'PAUNA',	15);
Insert Into Ciudades Values (	533,	'PAYA',	15);
Insert Into Ciudades Values (	537,	'PAZ DE RIO',	15);
Insert Into Ciudades Values (	542,	'PESCA',	15);
Insert Into Ciudades Values (	550,	'PISBA',	15);
Insert Into Ciudades Values (	572,	'PUERTO BOYACA',	15);
Insert Into Ciudades Values (	580,	'QUIPAMA',	15);
Insert Into Ciudades Values (	599,	'RAMIRIQUI',	15);
Insert Into Ciudades Values (	600,	'RAQUIRA',	15);
Insert Into Ciudades Values (	621,	'RONDON',	15);
Insert Into Ciudades Values (	632,	'SABOYA',	15);
Insert Into Ciudades Values (	638,	'SACHICA',	15);
Insert Into Ciudades Values (	646,	'SAMACA',	15);
Insert Into Ciudades Values (	660,	'SAN EDUARDO',	15);
Insert Into Ciudades Values (	664,	'SAN JOSE DE PARE',	15);
Insert Into Ciudades Values (	667,	'SAN LUIS DE GACENO',	15);
Insert Into Ciudades Values (	673,	'SAN MATEO',	15);
Insert Into Ciudades Values (	676,	'SAN MIGUEL DE SEMA',	15);
Insert Into Ciudades Values (	681,	'SAN PABLO DE BORBUR',	15);
Insert Into Ciudades Values (	686,	'SANTANA',	15);
Insert Into Ciudades Values (	690,	'SANTA MARIA',	15);
Insert Into Ciudades Values (	693,	'SANTA ROSA DE VITERBO',	15);
Insert Into Ciudades Values (	696,	'SANTA SOFIA',	15);
Insert Into Ciudades Values (	720,	'SATIVANORTE',	15);
Insert Into Ciudades Values (	723,	'SATIVASUR',	15);
Insert Into Ciudades Values (	740,	'SIACHOQUE',	15);
Insert Into Ciudades Values (	753,	'SOATA',	15);
Insert Into Ciudades Values (	755,	'SOCOTA',	15);
Insert Into Ciudades Values (	757,	'SOCHA',	15);
Insert Into Ciudades Values (	759,	'SOGAMOSO',	15);
Insert Into Ciudades Values (	761,	'SOMONDOCO',	15);
Insert Into Ciudades Values (	762,	'SORA',	15);
Insert Into Ciudades Values (	763,	'SOTAQUIRA',	15);
Insert Into Ciudades Values (	764,	'SORACA',	15);
Insert Into Ciudades Values (	774,	'SUSACON',	15);
Insert Into Ciudades Values (	776,	'SUTAMARCHAN',	15);
Insert Into Ciudades Values (	778,	'SUTATENZA',	15);
Insert Into Ciudades Values (	790,	'TASCO',	15);
Insert Into Ciudades Values (	798,	'TENZA',	15);
Insert Into Ciudades Values (	804,	'TIBANA',	15);
Insert Into Ciudades Values (	806,	'TIBASOSA',	15);
Insert Into Ciudades Values (	808,	'TINJACA',	15);
Insert Into Ciudades Values (	810,	'TIPACOQUE',	15);
Insert Into Ciudades Values (	814,	'TOCA',	15);
Insert Into Ciudades Values (	816,	'TOGsI',	15);
Insert Into Ciudades Values (	820,	'TOPAGA',	15);
Insert Into Ciudades Values (	822,	'TOTA',	15);
Insert Into Ciudades Values (	832,	'TUNUNGUA',	15);
Insert Into Ciudades Values (	835,	'TURMEQUE',	15);
Insert Into Ciudades Values (	837,	'TUTA',	15);
Insert Into Ciudades Values (	839,	'TUTAZA',	15);
Insert Into Ciudades Values (	842,	'UMBITA',	15);
Insert Into Ciudades Values (	861,	'VENTAQUEMADA',	15);
Insert Into Ciudades Values (	879,	'VIRACACHA',	15);
Insert Into Ciudades Values (	897,	'ZETAQUIRA',	15);
Insert Into Ciudades Values (	001,	'MANIZALES',	17);
Insert Into Ciudades Values (	013,	'AGUADAS',	17);
Insert Into Ciudades Values (	042,	'ANSERMA',	17);
Insert Into Ciudades Values (	050,	'ARANZAZU',	17);
Insert Into Ciudades Values (	088,	'BELALCAZAR',	17);
Insert Into Ciudades Values (	174,	'CHINCHINA',	17);
Insert Into Ciudades Values (	272,	'FILADELFIA',	17);
Insert Into Ciudades Values (	380,	'LA DORADA',	17);
Insert Into Ciudades Values (	388,	'LA MERCED',	17);
Insert Into Ciudades Values (	433,	'MANZANARES',	17);
Insert Into Ciudades Values (	442,	'MARMATO',	17);
Insert Into Ciudades Values (	444,	'MARQUETALIA',	17);
Insert Into Ciudades Values (	446,	'MARULANDA',	17);
Insert Into Ciudades Values (	486,	'NEIRA',	17);
Insert Into Ciudades Values (	495,	'NORCASIA',	17);
Insert Into Ciudades Values (	513,	'PACORA',	17);
Insert Into Ciudades Values (	524,	'PALESTINA',	17);
Insert Into Ciudades Values (	541,	'PENSILVANIA',	17);
Insert Into Ciudades Values (	614,	'RIOSUCIO',	17);
Insert Into Ciudades Values (	616,	'RISARALDA',	17);
Insert Into Ciudades Values (	653,	'SALAMINA',	17);
Insert Into Ciudades Values (	662,	'SAMANA',	17);
Insert Into Ciudades Values (	665,	'SAN JOSE',	17);
Insert Into Ciudades Values (	777,	'SUPIA',	17);
Insert Into Ciudades Values (	867,	'VICTORIA',	17);
Insert Into Ciudades Values (	873,	'VILLAMARIA',	17);
Insert Into Ciudades Values (	877,	'VITERBO',	17);
Insert Into Ciudades Values (	001,	'FLORENCIA',	18);
Insert Into Ciudades Values (	029,	'ALBANIA',	18);
Insert Into Ciudades Values (	094,	'BELEN DE LOS ANDAQUIES',	18);
Insert Into Ciudades Values (	150,	'CARTAGENA DEL CHAIRA',	18);
Insert Into Ciudades Values (	205,	'CURILLO',	18);
Insert Into Ciudades Values (	247,	'EL DONCELLO',	18);
Insert Into Ciudades Values (	256,	'EL PAUJIL',	18);
Insert Into Ciudades Values (	410,	'LA MONTAÑITA',	18);
Insert Into Ciudades Values (	460,	'MILAN',	18);
Insert Into Ciudades Values (	479,	'MORELIA',	18);
Insert Into Ciudades Values (	592,	'PUERTO RICO',	18);
Insert Into Ciudades Values (	610,	'SAN JOSE DEL FRAGUA',	18);
Insert Into Ciudades Values (	753,	'SAN VICENTE DEL CAGUAN',	18);
Insert Into Ciudades Values (	756,	'SOLANO',	18);
Insert Into Ciudades Values (	785,	'SOLITA',	18);
Insert Into Ciudades Values (	860,	'VALPARAISO',	18);
Insert Into Ciudades Values (	001,	'POPAYAN',	19);
Insert Into Ciudades Values (	022,	'ALMAGUER',	19);
Insert Into Ciudades Values (	050,	'ARGELIA',	19);
Insert Into Ciudades Values (	075,	'BALBOA',	19);
Insert Into Ciudades Values (	100,	'BOLIVAR',	19);
Insert Into Ciudades Values (	110,	'BUENOS AIRES',	19);
Insert Into Ciudades Values (	130,	'CAJIBIO',	19);
Insert Into Ciudades Values (	137,	'CALDONO',	19);
Insert Into Ciudades Values (	142,	'CALOTO',	19);
Insert Into Ciudades Values (	212,	'CORINTO',	19);
Insert Into Ciudades Values (	256,	'EL TAMBO',	19);
Insert Into Ciudades Values (	290,	'FLORENCIA',	19);
Insert Into Ciudades Values (	300,	'GUACHENE',	19);
Insert Into Ciudades Values (	318,	'GUAPI',	19);
Insert Into Ciudades Values (	355,	'INZA',	19);
Insert Into Ciudades Values (	364,	'JAMBALO',	19);
Insert Into Ciudades Values (	392,	'LA SIERRA',	19);
Insert Into Ciudades Values (	397,	'LA VEGA',	19);
Insert Into Ciudades Values (	418,	'LOPEZ',	19);
Insert Into Ciudades Values (	450,	'MERCADERES',	19);
Insert Into Ciudades Values (	455,	'MIRANDA',	19);
Insert Into Ciudades Values (	473,	'MORALES',	19);
Insert Into Ciudades Values (	513,	'PADILLA',	19);
Insert Into Ciudades Values (	517,	'PAEZ',	19);
Insert Into Ciudades Values (	532,	'PATIA',	19);
Insert Into Ciudades Values (	533,	'PIAMONTE',	19);
Insert Into Ciudades Values (	548,	'PIENDAMO',	19);
Insert Into Ciudades Values (	573,	'PUERTO TEJADA',	19);
Insert Into Ciudades Values (	585,	'PURACE',	19);
Insert Into Ciudades Values (	622,	'ROSAS',	19);
Insert Into Ciudades Values (	693,	'SAN SEBASTIAN',	19);
Insert Into Ciudades Values (	698,	'SANTANDER DE QUILICHAO',	19);
Insert Into Ciudades Values (	701,	'SANTA ROSA',	19);
Insert Into Ciudades Values (	743,	'SILVIA',	19);
Insert Into Ciudades Values (	760,	'SOTARA',	19);
Insert Into Ciudades Values (	780,	'SUAREZ',	19);
Insert Into Ciudades Values (	785,	'SUCRE',	19);
Insert Into Ciudades Values (	807,	'TIMBIO',	19);
Insert Into Ciudades Values (	809,	'TIMBIQUI',	19);
Insert Into Ciudades Values (	821,	'TORIBIO',	19);
Insert Into Ciudades Values (	824,	'TOTORO',	19);
Insert Into Ciudades Values (	845,	'VILLA RICA',	19);
Insert Into Ciudades Values (	001,	'VALLEDUPAR',	20);
Insert Into Ciudades Values (	011,	'AGUACHICA',	20);
Insert Into Ciudades Values (	013,	'AGUSTIN CODAZZI',	20);
Insert Into Ciudades Values (	032,	'ASTREA',	20);
Insert Into Ciudades Values (	045,	'BECERRIL',	20);
Insert Into Ciudades Values (	060,	'BOSCONIA',	20);
Insert Into Ciudades Values (	175,	'CHIMICHAGUA',	20);
Insert Into Ciudades Values (	178,	'CHIRIGUANA',	20);
Insert Into Ciudades Values (	228,	'CURUMANI',	20);
Insert Into Ciudades Values (	238,	'EL COPEY',	20);
Insert Into Ciudades Values (	250,	'EL PASO',	20);
Insert Into Ciudades Values (	295,	'GAMARRA',	20);
Insert Into Ciudades Values (	310,	'GONZALEZ',	20);
Insert Into Ciudades Values (	383,	'LA GLORIA',	20);
Insert Into Ciudades Values (	400,	'LA JAGUA DE IBIRICO',	20);
Insert Into Ciudades Values (	443,	'MANAURE',	20);
Insert Into Ciudades Values (	517,	'PAILITAS',	20);
Insert Into Ciudades Values (	550,	'PELAYA',	20);
Insert Into Ciudades Values (	570,	'PUEBLO BELLO',	20);
Insert Into Ciudades Values (	614,	'RIO DE ORO',	20);
Insert Into Ciudades Values (	621,	'LA PAZ',	20);
Insert Into Ciudades Values (	710,	'SAN ALBERTO',	20);
Insert Into Ciudades Values (	750,	'SAN DIEGO',	20);
Insert Into Ciudades Values (	770,	'SAN MARTIN',	20);
Insert Into Ciudades Values (	787,	'TAMALAMEQUE',	20);
Insert Into Ciudades Values (	001,	'MONTERIA',	23);
Insert Into Ciudades Values (	068,	'AYAPEL',	23);
Insert Into Ciudades Values (	079,	'BUENAVISTA',	23);
Insert Into Ciudades Values (	090,	'CANALETE',	23);
Insert Into Ciudades Values (	162,	'CERETE',	23);
Insert Into Ciudades Values (	168,	'CHIMA',	23);
Insert Into Ciudades Values (	182,	'CHINU',	23);
Insert Into Ciudades Values (	189,	'CIENAGA DE ORO',	23);
Insert Into Ciudades Values (	300,	'COTORRA',	23);
Insert Into Ciudades Values (	350,	'LA APARTADA',	23);
Insert Into Ciudades Values (	417,	'LORICA',	23);
Insert Into Ciudades Values (	419,	'LOS CORDOBAS',	23);
Insert Into Ciudades Values (	464,	'MOMIL',	23);
Insert Into Ciudades Values (	466,	'MONTELIBANO',	23);
Insert Into Ciudades Values (	500,	'MOÑITOS',	23);
Insert Into Ciudades Values (	555,	'PLANETA RICA',	23);
Insert Into Ciudades Values (	570,	'PUEBLO NUEVO',	23);
Insert Into Ciudades Values (	574,	'PUERTO ESCONDIDO',	23);
Insert Into Ciudades Values (	580,	'PUERTO LIBERTADOR',	23);
Insert Into Ciudades Values (	586,	'PURISIMA',	23);
Insert Into Ciudades Values (	660,	'SAHAGUN',	23);
Insert Into Ciudades Values (	670,	'SAN ANDRES SOTAVENTO',	23);
Insert Into Ciudades Values (	672,	'SAN ANTERO',	23);
Insert Into Ciudades Values (	675,	'SAN BERNARDO DEL VIENTO',	23);
Insert Into Ciudades Values (	678,	'SAN CARLOS',	23);
Insert Into Ciudades Values (	686,	'SAN PELAYO',	23);
Insert Into Ciudades Values (	807,	'TIERRALTA',	23);
Insert Into Ciudades Values (	855,	'VALENCIA',	23);
Insert Into Ciudades Values (	001,	'AGUA DE DIOS',	25);
Insert Into Ciudades Values (	019,	'ALBAN',	25);
Insert Into Ciudades Values (	035,	'ANAPOIMA',	25);
Insert Into Ciudades Values (	040,	'ANOLAIMA',	25);
Insert Into Ciudades Values (	053,	'ARBELAEZ',	25);
Insert Into Ciudades Values (	086,	'BELTRAN',	25);
Insert Into Ciudades Values (	095,	'BITUIMA',	25);
Insert Into Ciudades Values (	099,	'BOJACA',	25);
Insert Into Ciudades Values (	120,	'CABRERA',	25);
Insert Into Ciudades Values (	123,	'CACHIPAY',	25);
Insert Into Ciudades Values (	126,	'CAJICA',	25);
Insert Into Ciudades Values (	148,	'CAPARRAPI',	25);
Insert Into Ciudades Values (	151,	'CAQUEZA',	25);
Insert Into Ciudades Values (	154,	'CARMEN DE CARUPA',	25);
Insert Into Ciudades Values (	168,	'CHAGUANI',	25);
Insert Into Ciudades Values (	175,	'CHIA',	25);
Insert Into Ciudades Values (	178,	'CHIPAQUE',	25);
Insert Into Ciudades Values (	181,	'CHOACHI',	25);
Insert Into Ciudades Values (	183,	'CHOCONTA',	25);
Insert Into Ciudades Values (	200,	'COGUA',	25);
Insert Into Ciudades Values (	214,	'COTA',	25);
Insert Into Ciudades Values (	224,	'CUCUNUBA',	25);
Insert Into Ciudades Values (	245,	'EL COLEGIO',	25);
Insert Into Ciudades Values (	258,	'EL PEÑON',	25);
Insert Into Ciudades Values (	260,	'EL ROSAL',	25);
Insert Into Ciudades Values (	269,	'FACATATIVA',	25);
Insert Into Ciudades Values (	279,	'FOMEQUE',	25);
Insert Into Ciudades Values (	281,	'FOSCA',	25);
Insert Into Ciudades Values (	286,	'FUNZA',	25);
Insert Into Ciudades Values (	288,	'FUQUENE',	25);
Insert Into Ciudades Values (	290,	'FUSAGASUGA',	25);
Insert Into Ciudades Values (	293,	'GACHALA',	25);
Insert Into Ciudades Values (	295,	'GACHANCIPA',	25);
Insert Into Ciudades Values (	297,	'GACHETA',	25);
Insert Into Ciudades Values (	299,	'GAMA',	25);
Insert Into Ciudades Values (	307,	'GIRARDOT',	25);
Insert Into Ciudades Values (	312,	'GRANADA',	25);
Insert Into Ciudades Values (	317,	'GUACHETA',	25);
Insert Into Ciudades Values (	320,	'GUADUAS',	25);
Insert Into Ciudades Values (	322,	'GUASCA',	25);
Insert Into Ciudades Values (	324,	'GUATAQUI',	25);
Insert Into Ciudades Values (	326,	'GUATAVITA',	25);
Insert Into Ciudades Values (	328,	'GUAYABAL DE SIQUIMA',	25);
Insert Into Ciudades Values (	335,	'GUAYABETAL',	25);
Insert Into Ciudades Values (	339,	'GUTIERREZ',	25);
Insert Into Ciudades Values (	368,	'JERUSALEN',	25);
Insert Into Ciudades Values (	372,	'JUNIN',	25);
Insert Into Ciudades Values (	377,	'LA CALERA',	25);
Insert Into Ciudades Values (	386,	'LA MESA',	25);
Insert Into Ciudades Values (	394,	'LA PALMA',	25);
Insert Into Ciudades Values (	398,	'LA PEÑA',	25);
Insert Into Ciudades Values (	402,	'LA VEGA',	25);
Insert Into Ciudades Values (	407,	'LENGUAZAQUE',	25);
Insert Into Ciudades Values (	426,	'MACHETA',	25);
Insert Into Ciudades Values (	430,	'MADRID',	25);
Insert Into Ciudades Values (	436,	'MANTA',	25);
Insert Into Ciudades Values (	438,	'MEDINA',	25);
Insert Into Ciudades Values (	473,	'MOSQUERA',	25);
Insert Into Ciudades Values (	483,	'NARIÑO',	25);
Insert Into Ciudades Values (	486,	'NEMOCON',	25);
Insert Into Ciudades Values (	488,	'NILO',	25);
Insert Into Ciudades Values (	489,	'NIMAIMA',	25);
Insert Into Ciudades Values (	491,	'NOCAIMA',	25);
Insert Into Ciudades Values (	506,	'VENECIA',	25);
Insert Into Ciudades Values (	513,	'PACHO',	25);
Insert Into Ciudades Values (	518,	'PAIME',	25);
Insert Into Ciudades Values (	524,	'PANDI',	25);
Insert Into Ciudades Values (	530,	'PARATEBUENO',	25);
Insert Into Ciudades Values (	535,	'PASCA',	25);
Insert Into Ciudades Values (	572,	'PUERTO SALGAR',	25);
Insert Into Ciudades Values (	580,	'PULI',	25);
Insert Into Ciudades Values (	592,	'QUEBRADANEGRA',	25);
Insert Into Ciudades Values (	594,	'QUETAME',	25);
Insert Into Ciudades Values (	596,	'QUIPILE',	25);
Insert Into Ciudades Values (	599,	'APULO',	25);
Insert Into Ciudades Values (	612,	'RICAURTE',	25);
Insert Into Ciudades Values (	645,	'SAN ANTONIO DEL TEQUENDAMA',	25);
Insert Into Ciudades Values (	649,	'SAN BERNARDO',	25);
Insert Into Ciudades Values (	653,	'SAN CAYETANO',	25);
Insert Into Ciudades Values (	658,	'SAN FRANCISCO',	25);
Insert Into Ciudades Values (	662,	'SAN JUAN DE RIO SECO',	25);
Insert Into Ciudades Values (	718,	'SASAIMA',	25);
Insert Into Ciudades Values (	736,	'SESQUILE',	25);
Insert Into Ciudades Values (	740,	'SIBATE',	25);
Insert Into Ciudades Values (	743,	'SILVANIA',	25);
Insert Into Ciudades Values (	745,	'SIMIJACA',	25);
Insert Into Ciudades Values (	754,	'SOACHA',	25);
Insert Into Ciudades Values (	758,	'SOPO',	25);
Insert Into Ciudades Values (	769,	'SUBACHOQUE',	25);
Insert Into Ciudades Values (	772,	'SUESCA',	25);
Insert Into Ciudades Values (	777,	'SUPATA',	25);
Insert Into Ciudades Values (	779,	'SUSA',	25);
Insert Into Ciudades Values (	781,	'SUTATAUSA',	25);
Insert Into Ciudades Values (	785,	'TABIO',	25);
Insert Into Ciudades Values (	793,	'TAUSA',	25);
Insert Into Ciudades Values (	797,	'TENA',	25);
Insert Into Ciudades Values (	799,	'TENJO',	25);
Insert Into Ciudades Values (	805,	'TIBACUY',	25);
Insert Into Ciudades Values (	807,	'TIBIRITA',	25);
Insert Into Ciudades Values (	815,	'TOCAIMA',	25);
Insert Into Ciudades Values (	817,	'TOCANCIPA',	25);
Insert Into Ciudades Values (	823,	'TOPAIPI',	25);
Insert Into Ciudades Values (	839,	'UBALA',	25);
Insert Into Ciudades Values (	841,	'UBAQUE',	25);
Insert Into Ciudades Values (	843,	'VILLA DE SAN DIEGO DE UBATE',	25);
Insert Into Ciudades Values (	845,	'UNE',	25);
Insert Into Ciudades Values (	851,	'UTICA',	25);
Insert Into Ciudades Values (	862,	'VERGARA',	25);
Insert Into Ciudades Values (	867,	'VIANI',	25);
Insert Into Ciudades Values (	871,	'VILLAGOMEZ',	25);
Insert Into Ciudades Values (	873,	'VILLAPINZON',	25);
Insert Into Ciudades Values (	875,	'VILLETA',	25);
Insert Into Ciudades Values (	878,	'VIOTA',	25);
Insert Into Ciudades Values (	885,	'YACOPI',	25);
Insert Into Ciudades Values (	898,	'ZIPACON',	25);
Insert Into Ciudades Values (	899,	'ZIPAQUIRA',	25);
Insert Into Ciudades Values (	001,	'QUIBDO',	27);
Insert Into Ciudades Values (	006,	'ACANDI',	27);
Insert Into Ciudades Values (	025,	'ALTO BAUDO',	27);
Insert Into Ciudades Values (	050,	'ATRATO',	27);
Insert Into Ciudades Values (	073,	'BAGADO',	27);
Insert Into Ciudades Values (	075,	'BAHIA SOLANO',	27);
Insert Into Ciudades Values (	077,	'BAJO BAUDO',	27);
Insert Into Ciudades Values (	099,	'BOJAYA',	27);
Insert Into Ciudades Values (	135,	'EL CANTON DEL SAN PABLO',	27);
Insert Into Ciudades Values (	150,	'CARMEN DEL DARIEN',	27);
Insert Into Ciudades Values (	160,	'CERTEGUI',	27);
Insert Into Ciudades Values (	205,	'CONDOTO',	27);
Insert Into Ciudades Values (	245,	'EL CARMEN DE ATRATO',	27);
Insert Into Ciudades Values (	250,	'EL LITORAL DEL SAN JUAN',	27);
Insert Into Ciudades Values (	361,	'ISTMINA',	27);
Insert Into Ciudades Values (	372,	'JURADO',	27);
Insert Into Ciudades Values (	413,	'LLORO',	27);
Insert Into Ciudades Values (	425,	'MEDIO ATRATO',	27);
Insert Into Ciudades Values (	430,	'MEDIO BAUDO',	27);
Insert Into Ciudades Values (	450,	'MEDIO SAN JUAN',	27);
Insert Into Ciudades Values (	491,	'NOVITA',	27);
Insert Into Ciudades Values (	495,	'NUQUI',	27);
Insert Into Ciudades Values (	580,	'RIO IRO',	27);
Insert Into Ciudades Values (	600,	'RIO QUITO',	27);
Insert Into Ciudades Values (	615,	'RIOSUCIO',	27);
Insert Into Ciudades Values (	660,	'SAN JOSE DEL PALMAR',	27);
Insert Into Ciudades Values (	745,	'SIPI',	27);
Insert Into Ciudades Values (	787,	'TADO',	27);
Insert Into Ciudades Values (	800,	'UNGUIA',	27);
Insert Into Ciudades Values (	810,	'UNION PANAMERICANA',	27);
Insert Into Ciudades Values (	001,	'NEIVA',	41);
Insert Into Ciudades Values (	006,	'ACEVEDO',	41);
Insert Into Ciudades Values (	013,	'AGRADO',	41);
Insert Into Ciudades Values (	016,	'AIPE',	41);
Insert Into Ciudades Values (	020,	'ALGECIRAS',	41);
Insert Into Ciudades Values (	026,	'ALTAMIRA',	41);
Insert Into Ciudades Values (	078,	'BARAYA',	41);
Insert Into Ciudades Values (	132,	'CAMPOALEGRE',	41);
Insert Into Ciudades Values (	206,	'COLOMBIA',	41);
Insert Into Ciudades Values (	244,	'ELIAS',	41);
Insert Into Ciudades Values (	298,	'GARZON',	41);
Insert Into Ciudades Values (	306,	'GIGANTE',	41);
Insert Into Ciudades Values (	319,	'GUADALUPE',	41);
Insert Into Ciudades Values (	349,	'HOBO',	41);
Insert Into Ciudades Values (	357,	'IQUIRA',	41);
Insert Into Ciudades Values (	359,	'ISNOS',	41);
Insert Into Ciudades Values (	378,	'LA ARGENTINA',	41);
Insert Into Ciudades Values (	396,	'LA PLATA',	41);
Insert Into Ciudades Values (	483,	'NATAGA',	41);
Insert Into Ciudades Values (	503,	'OPORAPA',	41);
Insert Into Ciudades Values (	518,	'PAICOL',	41);
Insert Into Ciudades Values (	524,	'PALERMO',	41);
Insert Into Ciudades Values (	530,	'PALESTINA',	41);
Insert Into Ciudades Values (	548,	'PITAL',	41);
Insert Into Ciudades Values (	551,	'PITALITO',	41);
Insert Into Ciudades Values (	615,	'RIVERA',	41);
Insert Into Ciudades Values (	660,	'SALADOBLANCO',	41);
Insert Into Ciudades Values (	668,	'SAN AGUSTIN',	41);
Insert Into Ciudades Values (	676,	'SANTA MARIA',	41);
Insert Into Ciudades Values (	770,	'SUAZA',	41);
Insert Into Ciudades Values (	791,	'TARQUI',	41);
Insert Into Ciudades Values (	797,	'TESALIA',	41);
Insert Into Ciudades Values (	799,	'TELLO',	41);
Insert Into Ciudades Values (	801,	'TERUEL',	41);
Insert Into Ciudades Values (	807,	'TIMANA',	41);
Insert Into Ciudades Values (	872,	'VILLAVIEJA',	41);
Insert Into Ciudades Values (	885,	'YAGUARA',	41);
Insert Into Ciudades Values (	001,	'RIOHACHA',	44);
Insert Into Ciudades Values (	035,	'ALBANIA',	44);
Insert Into Ciudades Values (	078,	'BARRANCAS',	44);
Insert Into Ciudades Values (	090,	'DIBULLA',	44);
Insert Into Ciudades Values (	098,	'DISTRACCION',	44);
Insert Into Ciudades Values (	110,	'EL MOLINO',	44);
Insert Into Ciudades Values (	279,	'FONSECA',	44);
Insert Into Ciudades Values (	378,	'HATONUEVO',	44);
Insert Into Ciudades Values (	420,	'LA JAGUA DEL PILAR',	44);
Insert Into Ciudades Values (	430,	'MAICAO',	44);
Insert Into Ciudades Values (	560,	'MANAURE',	44);
Insert Into Ciudades Values (	650,	'SAN JUAN DEL CESAR',	44);
Insert Into Ciudades Values (	847,	'URIBIA',	44);
Insert Into Ciudades Values (	855,	'URUMITA',	44);
Insert Into Ciudades Values (	874,	'VILLANUEVA',	44);
Insert Into Ciudades Values (	001,	'SANTA MARTA',	47);
Insert Into Ciudades Values (	030,	'ALGARROBO',	47);
Insert Into Ciudades Values (	053,	'ARACATACA',	47);
Insert Into Ciudades Values (	058,	'ARIGUANI',	47);
Insert Into Ciudades Values (	161,	'CERRO SAN ANTONIO',	47);
Insert Into Ciudades Values (	170,	'CHIBOLO',	47);
Insert Into Ciudades Values (	189,	'CIENAGA',	47);
Insert Into Ciudades Values (	205,	'CONCORDIA',	47);
Insert Into Ciudades Values (	245,	'EL BANCO',	47);
Insert Into Ciudades Values (	258,	'EL PIÑON',	47);
Insert Into Ciudades Values (	268,	'EL RETEN',	47);
Insert Into Ciudades Values (	288,	'FUNDACION',	47);
Insert Into Ciudades Values (	318,	'GUAMAL',	47);
Insert Into Ciudades Values (	460,	'NUEVA GRANADA',	47);
Insert Into Ciudades Values (	541,	'PEDRAZA',	47);
Insert Into Ciudades Values (	545,	'PIJIÑO DEL CARMEN',	47);
Insert Into Ciudades Values (	551,	'PIVIJAY',	47);
Insert Into Ciudades Values (	555,	'PLATO',	47);
Insert Into Ciudades Values (	570,	'PUEBLOVIEJO',	47);
Insert Into Ciudades Values (	605,	'REMOLINO',	47);
Insert Into Ciudades Values (	660,	'SABANAS DE SAN ANGEL',	47);
Insert Into Ciudades Values (	675,	'SALAMINA',	47);
Insert Into Ciudades Values (	692,	'SAN SEBASTIAN DE BUENAVISTA',	47);
Insert Into Ciudades Values (	703,	'SAN ZENON',	47);
Insert Into Ciudades Values (	707,	'SANTA ANA',	47);
Insert Into Ciudades Values (	720,	'SANTA BARBARA DE PINTO',	47);
Insert Into Ciudades Values (	745,	'SITIONUEVO',	47);
Insert Into Ciudades Values (	798,	'TENERIFE',	47);
Insert Into Ciudades Values (	960,	'ZAPAYAN',	47);
Insert Into Ciudades Values (	980,	'ZONA BANANERA',	47);
Insert Into Ciudades Values (	001,	'VILLAVICENCIO',	50);
Insert Into Ciudades Values (	006,	'ACACIAS',	50);
Insert Into Ciudades Values (	110,	'BARRANCA DE UPIA',	50);
Insert Into Ciudades Values (	124,	'CABUYARO',	50);
Insert Into Ciudades Values (	150,	'CASTILLA LA NUEVA',	50);
Insert Into Ciudades Values (	223,	'CUBARRAL',	50);
Insert Into Ciudades Values (	226,	'CUMARAL',	50);
Insert Into Ciudades Values (	245,	'EL CALVARIO',	50);
Insert Into Ciudades Values (	251,	'EL CASTILLO',	50);
Insert Into Ciudades Values (	270,	'EL DORADO',	50);
Insert Into Ciudades Values (	287,	'FUENTE DE ORO',	50);
Insert Into Ciudades Values (	313,	'GRANADA',	50);
Insert Into Ciudades Values (	318,	'GUAMAL',	50);
Insert Into Ciudades Values (	325,	'MAPIRIPAN',	50);
Insert Into Ciudades Values (	330,	'MESETAS',	50);
Insert Into Ciudades Values (	350,	'LA MACARENA',	50);
Insert Into Ciudades Values (	370,	'URIBE',	50);
Insert Into Ciudades Values (	400,	'LEJANIAS',	50);
Insert Into Ciudades Values (	450,	'PUERTO CONCORDIA',	50);
Insert Into Ciudades Values (	568,	'PUERTO GAITAN',	50);
Insert Into Ciudades Values (	573,	'PUERTO LOPEZ',	50);
Insert Into Ciudades Values (	577,	'PUERTO LLERAS',	50);
Insert Into Ciudades Values (	590,	'PUERTO RICO',	50);
Insert Into Ciudades Values (	606,	'RESTREPO',	50);
Insert Into Ciudades Values (	680,	'SAN CARLOS DE GUAROA',	50);
Insert Into Ciudades Values (	683,	'SAN JUAN DE ARAMA',	50);
Insert Into Ciudades Values (	686,	'SAN JUANITO',	50);
Insert Into Ciudades Values (	689,	'SAN MARTIN',	50);
Insert Into Ciudades Values (	711,	'VISTAHERMOSA',	50);
Insert Into Ciudades Values (	001,	'PASTO',	52);
Insert Into Ciudades Values (	019,	'ALBAN',	52);
Insert Into Ciudades Values (	022,	'ALDANA',	52);
Insert Into Ciudades Values (	036,	'ANCUYA',	52);
Insert Into Ciudades Values (	051,	'ARBOLEDA',	52);
Insert Into Ciudades Values (	079,	'BARBACOAS',	52);
Insert Into Ciudades Values (	083,	'BELEN',	52);
Insert Into Ciudades Values (	110,	'BUESACO',	52);
Insert Into Ciudades Values (	203,	'COLON',	52);
Insert Into Ciudades Values (	207,	'CONSACA',	52);
Insert Into Ciudades Values (	210,	'CONTADERO',	52);
Insert Into Ciudades Values (	215,	'CORDOBA',	52);
Insert Into Ciudades Values (	224,	'CUASPUD',	52);
Insert Into Ciudades Values (	227,	'CUMBAL',	52);
Insert Into Ciudades Values (	233,	'CUMBITARA',	52);
Insert Into Ciudades Values (	240,	'CHACHAGsI',	52);
Insert Into Ciudades Values (	250,	'EL CHARCO',	52);
Insert Into Ciudades Values (	254,	'EL PEÑOL',	52);
Insert Into Ciudades Values (	256,	'EL ROSARIO',	52);
Insert Into Ciudades Values (	258,	'EL TABLON DE GOMEZ',	52);
Insert Into Ciudades Values (	260,	'EL TAMBO',	52);
Insert Into Ciudades Values (	287,	'FUNES',	52);
Insert Into Ciudades Values (	317,	'GUACHUCAL',	52);
Insert Into Ciudades Values (	320,	'GUAITARILLA',	52);
Insert Into Ciudades Values (	323,	'GUALMATAN',	52);
Insert Into Ciudades Values (	352,	'ILES',	52);
Insert Into Ciudades Values (	354,	'IMUES',	52);
Insert Into Ciudades Values (	356,	'IPIALES',	52);
Insert Into Ciudades Values (	378,	'LA CRUZ',	52);
Insert Into Ciudades Values (	381,	'LA FLORIDA',	52);
Insert Into Ciudades Values (	385,	'LA LLANADA',	52);
Insert Into Ciudades Values (	390,	'LA TOLA',	52);
Insert Into Ciudades Values (	399,	'LA UNION',	52);
Insert Into Ciudades Values (	405,	'LEIVA',	52);
Insert Into Ciudades Values (	411,	'LINARES',	52);
Insert Into Ciudades Values (	418,	'LOS ANDES',	52);
Insert Into Ciudades Values (	427,	'MAGsI',	52);
Insert Into Ciudades Values (	435,	'MALLAMA',	52);
Insert Into Ciudades Values (	473,	'MOSQUERA',	52);
Insert Into Ciudades Values (	480,	'NARIÑO',	52);
Insert Into Ciudades Values (	490,	'OLAYA HERRERA',	52);
Insert Into Ciudades Values (	506,	'OSPINA',	52);
Insert Into Ciudades Values (	520,	'FRANCISCO PIZARRO',	52);
Insert Into Ciudades Values (	540,	'POLICARPA',	52);
Insert Into Ciudades Values (	560,	'POTOSI',	52);
Insert Into Ciudades Values (	565,	'PROVIDENCIA',	52);
Insert Into Ciudades Values (	573,	'PUERRES',	52);
Insert Into Ciudades Values (	585,	'PUPIALES',	52);
Insert Into Ciudades Values (	612,	'RICAURTE',	52);
Insert Into Ciudades Values (	621,	'ROBERTO PAYAN',	52);
Insert Into Ciudades Values (	678,	'SAMANIEGO',	52);
Insert Into Ciudades Values (	683,	'SANDONA',	52);
Insert Into Ciudades Values (	685,	'SAN BERNARDO',	52);
Insert Into Ciudades Values (	687,	'SAN LORENZO',	52);
Insert Into Ciudades Values (	693,	'SAN PABLO',	52);
Insert Into Ciudades Values (	694,	'SAN PEDRO DE CARTAGO',	52);
Insert Into Ciudades Values (	696,	'SANTA BARBARA',	52);
Insert Into Ciudades Values (	699,	'SANTACRUZ',	52);
Insert Into Ciudades Values (	720,	'SAPUYES',	52);
Insert Into Ciudades Values (	786,	'TAMINANGO',	52);
Insert Into Ciudades Values (	788,	'TANGUA',	52);
Insert Into Ciudades Values (	835,	'SAN ANDRES DE TUMACO',	52);
Insert Into Ciudades Values (	838,	'TUQUERRES',	52);
Insert Into Ciudades Values (	885,	'YACUANQUER',	52);
Insert Into Ciudades Values (	001,	'CUCUTA',	54);
Insert Into Ciudades Values (	003,	'ABREGO',	54);
Insert Into Ciudades Values (	051,	'ARBOLEDAS',	54);
Insert Into Ciudades Values (	099,	'BOCHALEMA',	54);
Insert Into Ciudades Values (	109,	'BUCARASICA',	54);
Insert Into Ciudades Values (	125,	'CACOTA',	54);
Insert Into Ciudades Values (	128,	'CACHIRA',	54);
Insert Into Ciudades Values (	172,	'CHINACOTA',	54);
Insert Into Ciudades Values (	174,	'CHITAGA',	54);
Insert Into Ciudades Values (	206,	'CONVENCION',	54);
Insert Into Ciudades Values (	223,	'CUCUTILLA',	54);
Insert Into Ciudades Values (	239,	'DURANIA',	54);
Insert Into Ciudades Values (	245,	'EL CARMEN',	54);
Insert Into Ciudades Values (	250,	'EL TARRA',	54);
Insert Into Ciudades Values (	261,	'EL ZULIA',	54);
Insert Into Ciudades Values (	313,	'GRAMALOTE',	54);
Insert Into Ciudades Values (	344,	'HACARI',	54);
Insert Into Ciudades Values (	347,	'HERRAN',	54);
Insert Into Ciudades Values (	377,	'LABATECA',	54);
Insert Into Ciudades Values (	385,	'LA ESPERANZA',	54);
Insert Into Ciudades Values (	398,	'LA PLAYA',	54);
Insert Into Ciudades Values (	405,	'LOS PATIOS',	54);
Insert Into Ciudades Values (	418,	'LOURDES',	54);
Insert Into Ciudades Values (	480,	'MUTISCUA',	54);
Insert Into Ciudades Values (	498,	'OCAÑA',	54);
Insert Into Ciudades Values (	518,	'PAMPLONA',	54);
Insert Into Ciudades Values (	520,	'PAMPLONITA',	54);
Insert Into Ciudades Values (	553,	'PUERTO SANTANDER',	54);
Insert Into Ciudades Values (	599,	'RAGONVALIA',	54);
Insert Into Ciudades Values (	660,	'SALAZAR',	54);
Insert Into Ciudades Values (	670,	'SAN CALIXTO',	54);
Insert Into Ciudades Values (	673,	'SAN CAYETANO',	54);
Insert Into Ciudades Values (	680,	'SANTIAGO',	54);
Insert Into Ciudades Values (	720,	'SARDINATA',	54);
Insert Into Ciudades Values (	743,	'SILOS',	54);
Insert Into Ciudades Values (	800,	'TEORAMA',	54);
Insert Into Ciudades Values (	810,	'TIBU',	54);
Insert Into Ciudades Values (	820,	'TOLEDO',	54);
Insert Into Ciudades Values (	871,	'VILLA CARO',	54);
Insert Into Ciudades Values (	874,	'VILLA DEL ROSARIO',	54);
Insert Into Ciudades Values (	001,	'ARMENIA',	63);
Insert Into Ciudades Values (	111,	'BUENAVISTA',	63);
Insert Into Ciudades Values (	130,	'CALARCA',	63);
Insert Into Ciudades Values (	190,	'CIRCASIA',	63);
Insert Into Ciudades Values (	212,	'CORDOBA',	63);
Insert Into Ciudades Values (	272,	'FILANDIA',	63);
Insert Into Ciudades Values (	302,	'GENOVA',	63);
Insert Into Ciudades Values (	401,	'LA TEBAIDA',	63);
Insert Into Ciudades Values (	470,	'MONTENEGRO',	63);
Insert Into Ciudades Values (	548,	'PIJAO',	63);
Insert Into Ciudades Values (	594,	'QUIMBAYA',	63);
Insert Into Ciudades Values (	690,	'SALENTO',	63);
Insert Into Ciudades Values (	001,	'PEREIRA',	66);
Insert Into Ciudades Values (	045,	'APIA',	66);
Insert Into Ciudades Values (	075,	'BALBOA',	66);
Insert Into Ciudades Values (	088,	'BELEN DE UMBRIA',	66);
Insert Into Ciudades Values (	170,	'DOSQUEBRADAS',	66);
Insert Into Ciudades Values (	318,	'GUATICA',	66);
Insert Into Ciudades Values (	383,	'LA CELIA',	66);
Insert Into Ciudades Values (	400,	'LA VIRGINIA',	66);
Insert Into Ciudades Values (	440,	'MARSELLA',	66);
Insert Into Ciudades Values (	456,	'MISTRATO',	66);
Insert Into Ciudades Values (	572,	'PUEBLO RICO',	66);
Insert Into Ciudades Values (	594,	'QUINCHIA',	66);
Insert Into Ciudades Values (	682,	'SANTA ROSA DE CABAL',	66);
Insert Into Ciudades Values (	687,	'SANTUARIO',	66);
Insert Into Ciudades Values (	001,	'BUCARAMANGA',	68);
Insert Into Ciudades Values (	013,	'AGUADA',	68);
Insert Into Ciudades Values (	020,	'ALBANIA',	68);
Insert Into Ciudades Values (	051,	'ARATOCA',	68);
Insert Into Ciudades Values (	077,	'BARBOSA',	68);
Insert Into Ciudades Values (	079,	'BARICHARA',	68);
Insert Into Ciudades Values (	081,	'BARRANCABERMEJA',	68);
Insert Into Ciudades Values (	092,	'BETULIA',	68);
Insert Into Ciudades Values (	101,	'BOLIVAR',	68);
Insert Into Ciudades Values (	121,	'CABRERA',	68);
Insert Into Ciudades Values (	132,	'CALIFORNIA',	68);
Insert Into Ciudades Values (	147,	'CAPITANEJO',	68);
Insert Into Ciudades Values (	152,	'CARCASI',	68);
Insert Into Ciudades Values (	160,	'CEPITA',	68);
Insert Into Ciudades Values (	162,	'CERRITO',	68);
Insert Into Ciudades Values (	167,	'CHARALA',	68);
Insert Into Ciudades Values (	169,	'CHARTA',	68);
Insert Into Ciudades Values (	176,	'CHIMA',	68);
Insert Into Ciudades Values (	179,	'CHIPATA',	68);
Insert Into Ciudades Values (	190,	'CIMITARRA',	68);
Insert Into Ciudades Values (	207,	'CONCEPCION',	68);
Insert Into Ciudades Values (	209,	'CONFINES',	68);
Insert Into Ciudades Values (	211,	'CONTRATACION',	68);
Insert Into Ciudades Values (	217,	'COROMORO',	68);
Insert Into Ciudades Values (	229,	'CURITI',	68);
Insert Into Ciudades Values (	235,	'EL CARMEN DE CHUCURI',	68);
Insert Into Ciudades Values (	245,	'EL GUACAMAYO',	68);
Insert Into Ciudades Values (	250,	'EL PEÑON',	68);
Insert Into Ciudades Values (	255,	'EL PLAYON',	68);
Insert Into Ciudades Values (	264,	'ENCINO',	68);
Insert Into Ciudades Values (	266,	'ENCISO',	68);
Insert Into Ciudades Values (	271,	'FLORIAN',	68);
Insert Into Ciudades Values (	276,	'FLORIDABLANCA',	68);
Insert Into Ciudades Values (	296,	'GALAN',	68);
Insert Into Ciudades Values (	298,	'GAMBITA',	68);
Insert Into Ciudades Values (	307,	'GIRON',	68);
Insert Into Ciudades Values (	318,	'GUACA',	68);
Insert Into Ciudades Values (	320,	'GUADALUPE',	68);
Insert Into Ciudades Values (	322,	'GUAPOTA',	68);
Insert Into Ciudades Values (	324,	'GUAVATA',	68);
Insert Into Ciudades Values (	327,	'GsEPSA',	68);
Insert Into Ciudades Values (	344,	'HATO',	68);
Insert Into Ciudades Values (	368,	'JESUS MARIA',	68);
Insert Into Ciudades Values (	370,	'JORDAN',	68);
Insert Into Ciudades Values (	377,	'LA BELLEZA',	68);
Insert Into Ciudades Values (	385,	'LANDAZURI',	68);
Insert Into Ciudades Values (	397,	'LA PAZ',	68);
Insert Into Ciudades Values (	406,	'LEBRIJA',	68);
Insert Into Ciudades Values (	418,	'LOS SANTOS',	68);
Insert Into Ciudades Values (	425,	'MACARAVITA',	68);
Insert Into Ciudades Values (	432,	'MALAGA',	68);
Insert Into Ciudades Values (	444,	'MATANZA',	68);
Insert Into Ciudades Values (	464,	'MOGOTES',	68);
Insert Into Ciudades Values (	468,	'MOLAGAVITA',	68);
Insert Into Ciudades Values (	498,	'OCAMONTE',	68);
Insert Into Ciudades Values (	500,	'OIBA',	68);
Insert Into Ciudades Values (	502,	'ONZAGA',	68);
Insert Into Ciudades Values (	522,	'PALMAR',	68);
Insert Into Ciudades Values (	524,	'PALMAS DEL SOCORRO',	68);
Insert Into Ciudades Values (	533,	'PARAMO',	68);
Insert Into Ciudades Values (	547,	'PIEDECUESTA',	68);
Insert Into Ciudades Values (	549,	'PINCHOTE',	68);
Insert Into Ciudades Values (	572,	'PUENTE NACIONAL',	68);
Insert Into Ciudades Values (	573,	'PUERTO PARRA',	68);
Insert Into Ciudades Values (	575,	'PUERTO WILCHES',	68);
Insert Into Ciudades Values (	615,	'RIONEGRO',	68);
Insert Into Ciudades Values (	655,	'SABANA DE TORRES',	68);
Insert Into Ciudades Values (	669,	'SAN ANDRES',	68);
Insert Into Ciudades Values (	673,	'SAN BENITO',	68);
Insert Into Ciudades Values (	679,	'SAN GIL',	68);
Insert Into Ciudades Values (	682,	'SAN JOAQUIN',	68);
Insert Into Ciudades Values (	684,	'SAN JOSE DE MIRANDA',	68);
Insert Into Ciudades Values (	686,	'SAN MIGUEL',	68);
Insert Into Ciudades Values (	689,	'SAN VICENTE DE CHUCURI',	68);
Insert Into Ciudades Values (	705,	'SANTA BARBARA',	68);
Insert Into Ciudades Values (	720,	'SANTA HELENA DEL OPON',	68);
Insert Into Ciudades Values (	745,	'SIMACOTA',	68);
Insert Into Ciudades Values (	755,	'SOCORRO',	68);
Insert Into Ciudades Values (	770,	'SUAITA',	68);
Insert Into Ciudades Values (	773,	'SUCRE',	68);
Insert Into Ciudades Values (	780,	'SURATA',	68);
Insert Into Ciudades Values (	820,	'TONA',	68);
Insert Into Ciudades Values (	855,	'VALLE DE SAN JOSE',	68);
Insert Into Ciudades Values (	861,	'VELEZ',	68);
Insert Into Ciudades Values (	867,	'VETAS',	68);
Insert Into Ciudades Values (	872,	'VILLANUEVA',	68);
Insert Into Ciudades Values (	895,	'ZAPATOCA',	68);
Insert Into Ciudades Values (	001,	'SINCELEJO',	70);
Insert Into Ciudades Values (	110,	'BUENAVISTA',	70);
Insert Into Ciudades Values (	124,	'CAIMITO',	70);
Insert Into Ciudades Values (	204,	'COLOSO',	70);
Insert Into Ciudades Values (	215,	'COROZAL',	70);
Insert Into Ciudades Values (	221,	'COVEÑAS',	70);
Insert Into Ciudades Values (	230,	'CHALAN',	70);
Insert Into Ciudades Values (	233,	'EL ROBLE',	70);
Insert Into Ciudades Values (	235,	'GALERAS',	70);
Insert Into Ciudades Values (	265,	'GUARANDA',	70);
Insert Into Ciudades Values (	400,	'LA UNION',	70);
Insert Into Ciudades Values (	418,	'LOS PALMITOS',	70);
Insert Into Ciudades Values (	429,	'MAJAGUAL',	70);
Insert Into Ciudades Values (	473,	'MORROA',	70);
Insert Into Ciudades Values (	508,	'OVEJAS',	70);
Insert Into Ciudades Values (	523,	'PALMITO',	70);
Insert Into Ciudades Values (	670,	'SAMPUES',	70);
Insert Into Ciudades Values (	678,	'SAN BENITO ABAD',	70);
Insert Into Ciudades Values (	702,	'SAN JUAN DE BETULIA',	70);
Insert Into Ciudades Values (	708,	'SAN MARCOS',	70);
Insert Into Ciudades Values (	713,	'SAN ONOFRE',	70);
Insert Into Ciudades Values (	717,	'SAN PEDRO',	70);
Insert Into Ciudades Values (	742,	'SAN LUIS DE SINCE',	70);
Insert Into Ciudades Values (	771,	'SUCRE',	70);
Insert Into Ciudades Values (	820,	'SANTIAGO DE TOLU',	70);
Insert Into Ciudades Values (	823,	'TOLU VIEJO',	70);
Insert Into Ciudades Values (	001,	'IBAGUE',	73);
Insert Into Ciudades Values (	024,	'ALPUJARRA',	73);
Insert Into Ciudades Values (	026,	'ALVARADO',	73);
Insert Into Ciudades Values (	030,	'AMBALEMA',	73);
Insert Into Ciudades Values (	043,	'ANZOATEGUI',	73);
Insert Into Ciudades Values (	055,	'ARMERO',	73);
Insert Into Ciudades Values (	067,	'ATACO',	73);
Insert Into Ciudades Values (	124,	'CAJAMARCA',	73);
Insert Into Ciudades Values (	148,	'CARMEN DE APICALA',	73);
Insert Into Ciudades Values (	152,	'CASABIANCA',	73);
Insert Into Ciudades Values (	168,	'CHAPARRAL',	73);
Insert Into Ciudades Values (	200,	'COELLO',	73);
Insert Into Ciudades Values (	217,	'COYAIMA',	73);
Insert Into Ciudades Values (	226,	'CUNDAY',	73);
Insert Into Ciudades Values (	236,	'DOLORES',	73);
Insert Into Ciudades Values (	268,	'ESPINAL',	73);
Insert Into Ciudades Values (	270,	'FALAN',	73);
Insert Into Ciudades Values (	275,	'FLANDES',	73);
Insert Into Ciudades Values (	283,	'FRESNO',	73);
Insert Into Ciudades Values (	319,	'GUAMO',	73);
Insert Into Ciudades Values (	347,	'HERVEO',	73);
Insert Into Ciudades Values (	349,	'HONDA',	73);
Insert Into Ciudades Values (	352,	'ICONONZO',	73);
Insert Into Ciudades Values (	408,	'LERIDA',	73);
Insert Into Ciudades Values (	411,	'LIBANO',	73);
Insert Into Ciudades Values (	443,	'MARIQUITA',	73);
Insert Into Ciudades Values (	449,	'MELGAR',	73);
Insert Into Ciudades Values (	461,	'MURILLO',	73);
Insert Into Ciudades Values (	483,	'NATAGAIMA',	73);
Insert Into Ciudades Values (	504,	'ORTEGA',	73);
Insert Into Ciudades Values (	520,	'PALOCABILDO',	73);
Insert Into Ciudades Values (	547,	'PIEDRAS',	73);
Insert Into Ciudades Values (	555,	'PLANADAS',	73);
Insert Into Ciudades Values (	563,	'PRADO',	73);
Insert Into Ciudades Values (	585,	'PURIFICACION',	73);
Insert Into Ciudades Values (	616,	'RIOBLANCO',	73);
Insert Into Ciudades Values (	622,	'RONCESVALLES',	73);
Insert Into Ciudades Values (	624,	'ROVIRA',	73);
Insert Into Ciudades Values (	671,	'SALDAÑA',	73);
Insert Into Ciudades Values (	675,	'SAN ANTONIO',	73);
Insert Into Ciudades Values (	678,	'SAN LUIS',	73);
Insert Into Ciudades Values (	686,	'SANTA ISABEL',	73);
Insert Into Ciudades Values (	770,	'SUAREZ',	73);
Insert Into Ciudades Values (	854,	'VALLE DE SAN JUAN',	73);
Insert Into Ciudades Values (	861,	'VENADILLO',	73);
Insert Into Ciudades Values (	870,	'VILLAHERMOSA',	73);
Insert Into Ciudades Values (	873,	'VILLARRICA',	73);
Insert Into Ciudades Values (	001,	'CALI',	76);
Insert Into Ciudades Values (	020,	'ALCALA',	76);
Insert Into Ciudades Values (	036,	'ANDALUCIA',	76);
Insert Into Ciudades Values (	041,	'ANSERMANUEVO',	76);
Insert Into Ciudades Values (	054,	'ARGELIA',	76);
Insert Into Ciudades Values (	100,	'BOLIVAR',	76);
Insert Into Ciudades Values (	109,	'BUENAVENTURA',	76);
Insert Into Ciudades Values (	111,	'GUADALAJARA DE BUGA',	76);
Insert Into Ciudades Values (	113,	'BUGALAGRANDE',	76);
Insert Into Ciudades Values (	122,	'CAICEDONIA',	76);
Insert Into Ciudades Values (	126,	'CALIMA',	76);
Insert Into Ciudades Values (	130,	'CANDELARIA',	76);
Insert Into Ciudades Values (	147,	'CARTAGO',	76);
Insert Into Ciudades Values (	233,	'DAGUA',	76);
Insert Into Ciudades Values (	243,	'EL AGUILA',	76);
Insert Into Ciudades Values (	246,	'EL CAIRO',	76);
Insert Into Ciudades Values (	248,	'EL CERRITO',	76);
Insert Into Ciudades Values (	250,	'EL DOVIO',	76);
Insert Into Ciudades Values (	275,	'FLORIDA',	76);
Insert Into Ciudades Values (	306,	'GINEBRA',	76);
Insert Into Ciudades Values (	318,	'GUACARI',	76);
Insert Into Ciudades Values (	364,	'JAMUNDI',	76);
Insert Into Ciudades Values (	377,	'LA CUMBRE',	76);
Insert Into Ciudades Values (	400,	'LA UNION',	76);
Insert Into Ciudades Values (	403,	'LA VICTORIA',	76);
Insert Into Ciudades Values (	497,	'OBANDO',	76);
Insert Into Ciudades Values (	520,	'PALMIRA',	76);
Insert Into Ciudades Values (	563,	'PRADERA',	76);
Insert Into Ciudades Values (	606,	'RESTREPO',	76);
Insert Into Ciudades Values (	616,	'RIOFRIO',	76);
Insert Into Ciudades Values (	622,	'ROLDANILLO',	76);
Insert Into Ciudades Values (	670,	'SAN PEDRO',	76);
Insert Into Ciudades Values (	736,	'SEVILLA',	76);
Insert Into Ciudades Values (	823,	'TORO',	76);
Insert Into Ciudades Values (	828,	'TRUJILLO',	76);
Insert Into Ciudades Values (	834,	'TULUA',	76);
Insert Into Ciudades Values (	845,	'ULLOA',	76);
Insert Into Ciudades Values (	863,	'VERSALLES',	76);
Insert Into Ciudades Values (	869,	'VIJES',	76);
Insert Into Ciudades Values (	890,	'YOTOCO',	76);
Insert Into Ciudades Values (	892,	'YUMBO',	76);
Insert Into Ciudades Values (	895,	'ZARZAL',	76);
Insert Into Ciudades Values (	001,	'ARAUCA',	81);
Insert Into Ciudades Values (	065,	'ARAUQUITA',	81);
Insert Into Ciudades Values (	220,	'CRAVO NORTE',	81);
Insert Into Ciudades Values (	300,	'FORTUL',	81);
Insert Into Ciudades Values (	591,	'PUERTO RONDON',	81);
Insert Into Ciudades Values (	736,	'SARAVENA',	81);
Insert Into Ciudades Values (	794,	'TAME',	81);
Insert Into Ciudades Values (	001,	'YOPAL',	85);
Insert Into Ciudades Values (	010,	'AGUAZUL',	85);
Insert Into Ciudades Values (	015,	'CHAMEZA',	85);
Insert Into Ciudades Values (	125,	'HATO COROZAL',	85);
Insert Into Ciudades Values (	136,	'LA SALINA',	85);
Insert Into Ciudades Values (	139,	'MANI',	85);
Insert Into Ciudades Values (	162,	'MONTERREY',	85);
Insert Into Ciudades Values (	225,	'NUNCHIA',	85);
Insert Into Ciudades Values (	230,	'OROCUE',	85);
Insert Into Ciudades Values (	250,	'PAZ DE ARIPORO',	85);
Insert Into Ciudades Values (	263,	'PORE',	85);
Insert Into Ciudades Values (	279,	'RECETOR',	85);
Insert Into Ciudades Values (	300,	'SABANALARGA',	85);
Insert Into Ciudades Values (	315,	'SACAMA',	85);
Insert Into Ciudades Values (	325,	'SAN LUIS DE PALENQUE',	85);
Insert Into Ciudades Values (	400,	'TAMARA',	85);
Insert Into Ciudades Values (	410,	'TAURAMENA',	85);
Insert Into Ciudades Values (	430,	'TRINIDAD',	85);
Insert Into Ciudades Values (	440,	'VILLANUEVA',	85);
Insert Into Ciudades Values (	001,	'MOCOA',	86);
Insert Into Ciudades Values (	219,	'COLON',	86);
Insert Into Ciudades Values (	320,	'ORITO',	86);
Insert Into Ciudades Values (	568,	'PUERTO ASIS',	86);
Insert Into Ciudades Values (	569,	'PUERTO CAICEDO',	86);
Insert Into Ciudades Values (	571,	'PUERTO GUZMAN',	86);
Insert Into Ciudades Values (	573,	'LEGUIZAMO',	86);
Insert Into Ciudades Values (	749,	'SIBUNDOY',	86);
Insert Into Ciudades Values (	755,	'SAN FRANCISCO',	86);
Insert Into Ciudades Values (	757,	'SAN MIGUEL',	86);
Insert Into Ciudades Values (	760,	'SANTIAGO',	86);
Insert Into Ciudades Values (	865,	'VALLE DEL GUAMUEZ',	86);
Insert Into Ciudades Values (	885,	'VILLAGARZON',	86);
Insert Into Ciudades Values (	001,	'SAN ANDRES',	88);
Insert Into Ciudades Values (	564,	'PROVIDENCIA',	88);
Insert Into Ciudades Values (	001,	'LETICIA',	91);
Insert Into Ciudades Values (	263,	'EL ENCANTO',	91);
Insert Into Ciudades Values (	405,	'LA CHORRERA',	91);
Insert Into Ciudades Values (	407,	'LA PEDRERA',	91);
Insert Into Ciudades Values (	430,	'LA VICTORIA',	91);
Insert Into Ciudades Values (	460,	'MIRITI - PARANA',	91);
Insert Into Ciudades Values (	530,	'PUERTO ALEGRIA',	91);
Insert Into Ciudades Values (	536,	'PUERTO ARICA',	91);
Insert Into Ciudades Values (	540,	'PUERTO NARIÑO',	91);
Insert Into Ciudades Values (	669,	'PUERTO SANTANDER',	91);
Insert Into Ciudades Values (	798,	'TARAPACA',	91);
Insert Into Ciudades Values (	001,	'INIRIDA',	94);
Insert Into Ciudades Values (	343,	'BARRANCO MINAS',	94);
Insert Into Ciudades Values (	663,	'MAPIRIPANA',	94);
Insert Into Ciudades Values (	883,	'SAN FELIPE',	94);
Insert Into Ciudades Values (	884,	'PUERTO COLOMBIA',	94);
Insert Into Ciudades Values (	885,	'LA GUADALUPE',	94);
Insert Into Ciudades Values (	886,	'CACAHUAL',	94);
Insert Into Ciudades Values (	887,	'PANA PANA',	94);
Insert Into Ciudades Values (	888,	'MORICHAL',	94);
Insert Into Ciudades Values (	001,	'SAN JOSE DEL GUAVIARE',	95);
Insert Into Ciudades Values (	015,	'CALAMAR',	95);
Insert Into Ciudades Values (	025,	'EL RETORNO',	95);
Insert Into Ciudades Values (	200,	'MIRAFLORES',	95);
Insert Into Ciudades Values (	001,	'MITU',	97);
Insert Into Ciudades Values (	161,	'CARURU',	97);
Insert Into Ciudades Values (	511,	'PACOA',	97);
Insert Into Ciudades Values (	666,	'TARAIRA',	97);
Insert Into Ciudades Values (	777,	'PAPUNAUA',	97);
Insert Into Ciudades Values (	889,	'YAVARATE',	97);
Insert Into Ciudades Values (	001,	'PUERTO CARREÑO',	99);
Insert Into Ciudades Values (	524,	'LA PRIMAVERA',	99);
Insert Into Ciudades Values (	624,	'SANTA ROSALIA',	99);
Insert Into Ciudades Values (	773,	'CUMARIBO',	99);
